Repository Plant-for-the-Planet-org/planet-donations, pull requests merged in 2022-04, with the labels that each got.

#269 Release 25 March
  README.md
  cypress/integration/languageTest.spec.js
  package-lock.json
  package.json
  pages/index.tsx
  public/assets/icons/UNEPLogo.tsx
  public/locales/de/common.json
  public/locales/es/common.json
  public/locales/fr/common.json
  public/locales/it/common.json
  public/locales/pt-BR/common.json
  src/Donations/Micros/PaymentStatus/SuccessfulDonation.tsx
  src/Donations/PaymentMethods/NewPaypal.tsx
  src/Donations/PaymentMethods/PaymentFunctions.ts
  src/Donations/index.tsx
  src/Layout/Footer.tsx
  src/Utils/api.ts
  styles/footer.scss
Labels: PR: reviewed-approved

#262 Feature/planet-cash-donation
  package-lock.json
  pages/index.tsx
  public/locales/en/common.json
  src/Common/InputTypes/ToggleSwitch.tsx
  src/Donations/Components/DonationsForm.tsx
  src/Donations/Components/PaymentStatus.tsx
  src/Donations/Components/PaymentsForm.tsx
  src/Donations/Micros/DonationTypes/BouquetDonations.tsx
  src/Donations/Micros/DonationTypes/FundingDonations.tsx
  src/Donations/Micros/DonationTypes/TreeDonation.tsx
  src/Donations/Micros/GiftForm.tsx
  src/Donations/Micros/OnBehalf.tsx
  src/Donations/Micros/PaymentStatus/SuccessfulDonation.tsx
  src/Donations/Micros/PaymentStatus/ThankyouMessage.tsx
  src/Donations/Micros/PlanetCashSelector.tsx
  src/Donations/Micros/TaxDeductionOption.tsx
  src/Donations/PaymentMethods/PaymentFunctions.ts
  src/Donations/PaymentMethods/PaymentMethodTabs.tsx
  src/Donations/PaymentMethods/PaymentRequestCustomButton.tsx
  src/Donations/index.tsx
  src/Layout/QueryParamContext.tsx
  src/Utils/api.ts
  src/Utils/cleanObject.ts
  styles/donations.scss
  styles/footer.scss
Labels: PR: unreviewed

#279 Allow user to add balance when pCash amount is not enough
  src/Donations/Micros/PlanetCashSelector.tsx
  src/Layout/Header.tsx
Labels: PR: unreviewed

#268 Avoid crash for missing lastname from Google Pay
  src/Donations/Components/DonationsForm.tsx
Labels: PR: partially-approved

#281 translate purpose string in thank you message
  public/locales/de/common.json
  public/locales/en/common.json
  public/locales/en/country.json
  src/Donations/Micros/PaymentStatus/ThankyouMessage.tsx
Labels: PR: unreviewed
