Repository Plant-for-the-Planet-org/planet-donations, pull requests merged in 2022-09, with the labels that each got.

#319 Fix not appending gift in request payload bug
  src/Donations/Micros/GiftForm.tsx
Labels: PR: reviewed-approved

#321 Allow user to topup planetcash with queryToken
  pages/index.tsx
  src/Donations/Components/DonationsForm.tsx
  src/Donations/Micros/PlanetCashSignup.tsx
  src/Layout/QueryParamContext.tsx
Labels: PR: partially-approved

#324 Deativate planetCash for monthly and yearly for gpay button
  src/Donations/Micros/PlanetCashSelector.tsx
Labels: PR: partially-approved

#323 OG:Image
  api/image.ts
  package-lock.json
  package.json
  pages/index.tsx
  src/Donations/Micros/ShareOptions.tsx
Labels: PR: partially-approved

#326 mobile view back button
  src/Donations/index.tsx
  styles/donations.scss
Labels: PR: reviewed-approved

#325 Release September 22nd, 2022
  api/image.ts
  package-lock.json
  package.json
  pages/index.tsx
  src/Donations/Components/DonationsForm.tsx
  src/Donations/Micros/GiftForm.tsx
  src/Donations/Micros/PlanetCashSelector.tsx
  src/Donations/Micros/PlanetCashSignup.tsx
  src/Donations/Micros/ShareOptions.tsx
  src/Donations/index.tsx
  src/Layout/QueryParamContext.tsx
  styles/donations.scss
Labels: PR: reviewed-approved

#331 fix: fix crash due to null tpo name for project
  src/Donations/Components/SelectProject.tsx
Labels: PR: unreviewed

#332 #331 fix crash due to null name
  src/Donations/Components/SelectProject.tsx
Labels: PR: unreviewed
