Repository Plant-for-the-Planet-org/planet-donations, pull requests merged in 2023-04, with the labels that each got.

#397 Release: April 2023 - Next 13 Upgrade
  .eslintrc.js
  @types/i18next.d.ts
  i18n.json
  middleware.ts
  next-i18next.config.js
  next.config.js
  package-lock.json
  package.json
  pages/_app.tsx
  pages/auth.tsx
  pages/index.tsx
  public/locales/cs/common.json
  public/locales/de/common.json
  public/locales/en/common.json
  public/locales/es/common.json
  public/locales/fr/common.json
  public/locales/it/common.json
  public/locales/pt-BR/common.json
  src/Common/AuthInterstitial/AuthInterstitial.module.scss
  src/Common/AuthInterstitial/index.tsx
  src/Common/Types/index.tsx
  src/Donations/Components/DonationsForm.tsx
  src/Donations/Components/PaymentStatus.tsx
  src/Donations/Components/PaymentsForm.tsx
  src/Donations/Micros/Authentication.tsx
  src/Donations/Micros/PaymentStatus/SuccessfulDonation.tsx
  src/Donations/Micros/PlanetCashSignup.tsx
  src/Donations/PaymentMethods/PaymentFunctions.ts
  src/Donations/PaymentMethods/PaymentRequestCustomButton.tsx
  src/Donations/index.tsx
  src/Layout/Footer.tsx
  src/Layout/QueryParamContext.tsx
  src/Utils/api.ts
  src/Utils/stripe/getStripe.tsx
Labels: PR: reviewed-approved

#396 Shows project details on context page
  src/Donations/index.tsx
Labels: PR: reviewed-approved

#393 Fixes payment retry issue where user got stuck on "Seeding your donation"
  src/Donations/Components/PaymentsForm.tsx
Labels: PR: reviewed-approved

#399 Release April: Small fixes
  src/Donations/Components/PaymentsForm.tsx
  src/Donations/index.tsx
Labels: PR: reviewed-approved

#401 Release: Update Config URL
  .env.production
  next.config.js
  src/Layout/QueryParamContext.tsx
Labels: PR: reviewed-approved

#398 Feature/use common types
  package-lock.json
  package.json
  pages/index.tsx
  src/Common/Types/QueryParamContextInterface.ts
  src/Common/Types/donation.d.ts
  src/Common/Types/index.tsx
  src/Donations/Components/ContactsForm.tsx
  src/Donations/Components/DonationsForm.tsx
  src/Donations/Components/PaymentStatus.tsx
  src/Donations/Components/PaymentsForm.tsx
  src/Donations/Micros/Authentication.tsx
  src/Donations/Micros/GiftForm.tsx
  src/Donations/Micros/PaymentStatus/FailedDonation.tsx
  src/Donations/Micros/PaymentStatus/ImageComponent.tsx
  src/Donations/Micros/PaymentStatus/SuccessfulDonation.tsx
  src/Donations/Micros/PaymentStatus/Tenants/SuccessfulDonationJane.tsx
  src/Donations/Micros/PaymentStatus/ThankyouMessage.tsx
  src/Donations/Micros/PaymentStatus/TransferDetails.tsx
  src/Donations/Micros/ShareOptions.tsx
  src/Donations/PaymentMethods/BankTransfer.tsx
  src/Donations/PaymentMethods/CardPayments.tsx
  src/Donations/PaymentMethods/GiroPayPayments.tsx
  src/Donations/PaymentMethods/NewPaypal.tsx
  src/Donations/PaymentMethods/PaymentFunctions.ts
  src/Donations/PaymentMethods/SepaPayments.tsx
  src/Donations/PaymentMethods/SofortPayment.tsx
  src/Layout/QueryParamContext.tsx
  src/Utils/countryUtils.ts
  src/Utils/projects/filterProjects.ts
Labels: PR: unreviewed

#402 Release common types
  package-lock.json
  package.json
  pages/index.tsx
  src/Common/Types/QueryParamContextInterface.ts
  src/Common/Types/donation.d.ts
  src/Common/Types/index.tsx
  src/Donations/Components/ContactsForm.tsx
  src/Donations/Components/DonationsForm.tsx
  src/Donations/Components/PaymentStatus.tsx
  src/Donations/Components/PaymentsForm.tsx
  src/Donations/Micros/Authentication.tsx
  src/Donations/Micros/GiftForm.tsx
  src/Donations/Micros/PaymentStatus/FailedDonation.tsx
  src/Donations/Micros/PaymentStatus/ImageComponent.tsx
  src/Donations/Micros/PaymentStatus/SuccessfulDonation.tsx
  src/Donations/Micros/PaymentStatus/Tenants/SuccessfulDonationJane.tsx
  src/Donations/Micros/PaymentStatus/ThankyouMessage.tsx
  src/Donations/Micros/PaymentStatus/TransferDetails.tsx
  src/Donations/Micros/ShareOptions.tsx
  src/Donations/PaymentMethods/BankTransfer.tsx
  src/Donations/PaymentMethods/CardPayments.tsx
  src/Donations/PaymentMethods/GiroPayPayments.tsx
  src/Donations/PaymentMethods/NewPaypal.tsx
  src/Donations/PaymentMethods/PaymentFunctions.ts
  src/Donations/PaymentMethods/SepaPayments.tsx
  src/Donations/PaymentMethods/SofortPayment.tsx
  src/Layout/QueryParamContext.tsx
  src/Utils/countryUtils.ts
  src/Utils/projects/filterProjects.ts
Labels: PR: reviewed-approved

#407 Top and verified projects (new)
  package-lock.json
  package.json
  pages/index.tsx
  public/locales/de/common.json
  public/locales/en/common.json
  src/Common/Types/index.tsx
  src/Donations/index.tsx
  src/Layout/QueryParamContext.tsx
  styles/donations.scss
  styles/globals.scss
Labels: PR: reviewed-approved, next in line, Priority

#410 Release Verified & Top-Projects
  package-lock.json
  package.json
  pages/index.tsx
  public/locales/cs/common.json
  public/locales/de/common.json
  public/locales/en/common.json
  public/locales/es/common.json
  public/locales/fr/common.json
  public/locales/it/common.json
  public/locales/pt-BR/common.json
  src/Common/Types/index.tsx
  src/Donations/index.tsx
  src/Layout/QueryParamContext.tsx
  styles/donations.scss
  styles/globals.scss
Labels: PR: reviewed-approved
