Repository Plant-for-the-Planet-org/planet-donations, pull requests merged in 2023-02, with the labels that each got.

#368 Release Donation Feb 2nd, 2023
  .eslintrc.js
  .husky/pre-commit
  husky-prepare.js
  package-lock.json
  package.json
  pages/index.tsx
  public/assets/icons/donation/BrowserPayIcon.tsx
  public/locales/cs/common.json
  public/locales/de/common.json
  public/locales/en/common.json
  public/locales/es/common.json
  public/locales/fr/common.json
  public/locales/it/common.json
  public/locales/pt-BR/common.json
  src/Common/Types/QueryParamContextInterface.ts
  src/Common/Types/donation.d.ts
  src/Common/Types/index.tsx
  src/Donations/Components/DonationsForm.tsx
  src/Donations/Components/PaymentsForm.tsx
  src/Donations/Micros/PaymentStatus/FailedDonation.tsx
  src/Donations/PaymentMethods/PaymentFunctions.ts
  src/Donations/PaymentMethods/PaymentRequestCustomButton.tsx
  src/Layout/QueryParamContext.tsx
  src/Utils/browsercheck.ts
Labels: PR: reviewed-approved

#372 added tracking-id header
  .env.production
  next.config.js
  src/Utils/api.ts
Labels: PR: partially-approved

#373 Minor release Feb 6th, 2023
  .env.production
  next.config.js
  src/Utils/api.ts
Labels: PR: partially-approved

#371 Allow recurrent donations with bank transfer
  public/locales/en/common.json
  src/Donations/Components/PaymentsForm.tsx
  src/Donations/Micros/PaymentStatus/TransferDetails.tsx
Labels: PR: reviewed-approved

#377 Release recurrent donations bank transfer (Feb 7th, 2023)
  public/locales/cs/common.json
  public/locales/de/common.json
  public/locales/en/common.json
  public/locales/es/common.json
  public/locales/fr/common.json
  public/locales/it/common.json
  public/locales/pt-BR/common.json
  src/Donations/Components/PaymentsForm.tsx
  src/Donations/Micros/PaymentStatus/TransferDetails.tsx
Labels: PR: reviewed-approved

#379 Release: Improved error handling (Feb 7th, 2023)
  package-lock.json
  package.json
  public/assets/icons/CloseIcon.tsx
  public/locales/de/common.json
  public/locales/en/common.json
  src/Common/ErrorPopup/ErrorPopup.module.scss
  src/Common/ErrorPopup/ErrorPopup.tsx
  src/Common/Types/QueryParamContextInterface.ts
  src/Donations/Components/DonationsForm.tsx
  src/Donations/Components/PaymentStatus.tsx
  src/Donations/Components/PaymentsForm.tsx
  src/Donations/Micros/Authentication.tsx
  src/Donations/Micros/PlanetCashSignup.tsx
  src/Layout/QueryParamContext.tsx
  src/Utils/api.ts
Labels: PR: reviewed-approved

#374 Handle gift data for failed donations
  pages/index.tsx
  src/Common/Types/QueryParamContextInterface.ts
  src/Common/Types/donation.d.ts
  src/Common/Types/index.tsx
  src/Donations/Micros/GiftForm.tsx
  src/Donations/Micros/PaymentStatus/FailedDonation.tsx
  src/Donations/PaymentMethods/PaymentFunctions.ts
  src/Layout/QueryParamContext.tsx
Labels: PR: unreviewed

#382 rebase develop
  pages/index.tsx
  src/Common/Types/QueryParamContextInterface.ts
  src/Common/Types/donation.d.ts
  src/Common/Types/index.tsx
  src/Donations/Micros/GiftForm.tsx
  src/Donations/Micros/PaymentStatus/FailedDonation.tsx
  src/Donations/PaymentMethods/PaymentFunctions.ts
  src/Layout/QueryParamContext.tsx
Labels: PR: reviewed-approved

#383 Upgrade react hook form to v7 (for next 13 update)
  package-lock.json
  package.json
  src/Common/InputTypes/MaterialTextField.tsx
  src/Donations/Components/ContactsForm.tsx
  src/Donations/Micros/Authentication.tsx
  src/Donations/Micros/GiftForm.tsx
  src/Donations/Micros/OnBehalf.tsx
  src/Layout/QueryParamContext.tsx
Labels: PR: reviewed-approved

#381 Upgrade mui version and react-hook-forms (for next 13 update)
  package-lock.json
  package.json
  pages/_app.tsx
  pages/_document.tsx
  src/Common/ContentLoaders/Donations/PaymentProgress.tsx
  src/Common/InputTypes/AutoCompleteCountry.tsx
  src/Common/InputTypes/CheckBox.tsx
  src/Common/InputTypes/GreenRadio.tsx
  src/Common/InputTypes/MaterialTextField.tsx
  src/Common/InputTypes/ToggleSwitch.tsx
  src/Donations/Components/ContactsForm.tsx
  src/Donations/Components/DonationsForm.tsx
  src/Donations/Components/PaymentStatus.tsx
  src/Donations/Micros/Authentication.tsx
  src/Donations/Micros/GiftForm.tsx
  src/Donations/Micros/OnBehalf.tsx
  src/Donations/Micros/PlanetCashSignup.tsx
  src/Donations/Micros/SelectCurrencyModal.tsx
  src/Donations/Micros/TaxDeductionCountryModal.tsx
  src/Donations/PaymentMethods/CardPayments.tsx
  src/Donations/PaymentMethods/SepaPayments.tsx
  src/Layout/Footer.tsx
  src/Layout/QueryParamContext.tsx
  styles/createEmotionCache.ts
  styles/muiTheme.ts
Labels: PR: unreviewed

#386 Release: update MUI and React Hook Form libraries.
  package-lock.json
  package.json
  pages/_app.tsx
  pages/_document.tsx
  src/Common/ContentLoaders/Donations/PaymentProgress.tsx
  src/Common/InputTypes/AutoCompleteCountry.tsx
  src/Common/InputTypes/CheckBox.tsx
  src/Common/InputTypes/GreenRadio.tsx
  src/Common/InputTypes/MaterialTextField.tsx
  src/Common/InputTypes/ToggleSwitch.tsx
  src/Donations/Components/ContactsForm.tsx
  src/Donations/Components/DonationsForm.tsx
  src/Donations/Components/PaymentStatus.tsx
  src/Donations/Micros/Authentication.tsx
  src/Donations/Micros/GiftForm.tsx
  src/Donations/Micros/OnBehalf.tsx
  src/Donations/Micros/PlanetCashSignup.tsx
  src/Donations/Micros/SelectCurrencyModal.tsx
  src/Donations/Micros/TaxDeductionCountryModal.tsx
  src/Donations/PaymentMethods/CardPayments.tsx
  src/Donations/PaymentMethods/SepaPayments.tsx
  src/Layout/Footer.tsx
  src/Layout/QueryParamContext.tsx
  styles/createEmotionCache.ts
  styles/muiTheme.ts
Labels: PR: reviewed-approved

#388 Restricts display of company name / toggle
  public/locales/en/common.json
  src/Donations/Components/ContactsForm.tsx
  src/Donations/Micros/Authentication.tsx
Labels: PR: reviewed-approved

#390 Release change toggle switch company donations
  public/locales/de/common.json
  public/locales/en/common.json
  src/Donations/Components/ContactsForm.tsx
  src/Donations/Micros/Authentication.tsx
Labels: PR: reviewed-approved
